schema_version = "1.0.0"
id = "absolute_scale"
name = "Absolute Scale"
version = "1.0.0"
tagline = "Scales selected elements in mesh edit mode to specified dimensions"
maintainer = "Martynas Žiemys"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
copyright = ["Martynas Žiemys"]